### ISSUE TITLE
info.database = os.path.join(app.root_path, info.database) AttributeError: can't set attribute

### ISSUE THREAD

**Issue by be-great** [PacktPublishing/Mastering-Flask-Web-Development-Second-Edition#10]
the Flask-SQLAlchemy==2.3.2, The version needs to be >= 2.5

**Comment by dpgaspar** [comment]
@be-great thank you for reaching out.

These are getting outdated, but did a quick test and

```
blinker
Flask==1.0.2
Flask-Login==0.4.1
Flask-SQLAlchemy==2.3.2
Flask-Migrate==2.1.1
Flask-WTF==0.14.2
flask-restful
flask-jwt-extended
flask-bcrypt
flask-openid
flask-dance
Faker==0.8.13
```

The previous install just fine. I like pinned dependencies. Can you elaborate more on why?
