### ISSUE TITLE
Missing element in requirements.txt - all chapters

### ISSUE THREAD

**Issue by kaalkop** [PacktPublishing/Mastering-Flask-Web-Development-Second-Edition#9]
Hi,
It may be that I missed something during the setup.  I run Ubuntu 20.04.

I had to add this line to requirements.txt before running the init.sh every time, otherwise the data generation failed
werkzeug==0.16.1

Regards
Barend

**Comment by JackStouffer** [comment]
@kaalkop If you don't add the line to the requirements file, can you post the results of the command `pip freeze`?

**Comment by deepesh-packt** [comment]
Please reopen the issue if the issue still persists.
